#!/bin/bash
script_path="$0"

p=$(dirname $script_path)
p=`cd "$p" && pwd`
cd $p/../..
#mvn -o -P production clean package assembly:single
#mvn -o clean test
mvn -o -P production -Dmaven.test.skip=true clean assembly:assembly

#dist dir
dist_dir=$p/../../target/dist/db-migration
mkdir -p $dist_dir

#binary dir
binary_path=$dist_dir/bin
mkdir -p $binary_path

#lib_dir
lib_dir=$dist_dir/lib
mkdir -p $lib_dir

#var_dir
var_dir=$dist_dir/var
mkdir -p $var_dir

#copy jar filie
#cp $p/../../target/db-migration-full.jar $lib_dir/

#package linux executor
cp -r $p/linux/bin/* ${binary_path}/

#package win executor
cp -r $p/win/bin/* ${binary_path}/
cd $p/win
~/DevTools/exe4j/bin/exe4jc db-migration.exe4j
mv db-migration.exe ${binary_path}/
cp db-migration.exe.vmoptions ${binary_path}/

cd $p
#copy example configruation files
cp -r ../config $dist_dir/
#copy doc files
cp -r ../doc $dist_dir/
cp  ../doc/changelog.txt $dist_dir/
cd $dist_dir
#remove subversion files
find . -name '.svn'|xargs rm -rf 
cd ..
tar cfvz db-migration-`date +%Y.%m.%d`.tar.gz db-migration
cd $p

